version: '2'

services:
    mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - /data/db

    mongo-express:
        image: mongo-express:latest
        ports:
          - 8081:8081
        depends_on:
          - mongo

    java-app:
        image: docktoranton/my-repo:myfirstimagepush
        ports:
          - 8080:8080
        environment:
          DB_HOST: mongo
          DB_PORT: 27017
          DB_NAME: db-prod
          SPRING_PROFILES_ACTIVE: prod
        depends_on:
          - mongo